import type { Doctor, Appointment, SpecialtyOption } from '../src/types';

export const doctors: Doctor[] = [
  {
    id: "d1",
    name: "Dr. Sarah Ahmed",
    specialty: "general",
    hospital: "City Medical Center",
    location: "Downtown, Building A",
    rating: 4.8,
    reviewCount: 124,
    experience: 12,
    fee: 50,
    currency: "USD",
    availableDays: ["Monday", "Tuesday", "Wednesday", "Thursday"],
    bio: "Dr. Sarah Ahmed is a board-certified general practitioner with over 12 years of experience. She specializes in preventive care and chronic disease management.",
    image: "/images/doctor-1.jpg"
  },
  {
    id: "d2",
    name: "Dr. Michael Chen",
    specialty: "cardiology",
    hospital: "Heart & Vascular Institute",
    location: "Medical District, Tower B",
    rating: 4.9,
    reviewCount: 89,
    experience: 18,
    fee: 120,
    currency: "USD",
    availableDays: ["Monday", "Wednesday", "Friday"],
    bio: "Dr. Michael Chen is a leading cardiologist specializing in interventional cardiology and heart failure management. He has performed over 2000 cardiac procedures.",
    image: "/images/doctor-2.jpg"
  },
  {
    id: "d3",
    name: "Dr. Emily Watson",
    specialty: "dermatology",
    hospital: "Skin Care Clinic",
    location: "Westside Medical Plaza",
    rating: 4.7,
    reviewCount: 156,
    experience: 8,
    fee: 80,
    currency: "USD",
    availableDays: ["Tuesday", "Thursday", "Saturday"],
    bio: "Dr. Emily Watson is a dermatologist specializing in medical and cosmetic dermatology. She treats conditions ranging from acne to skin cancer.",
    image: "/images/doctor-3.jpg"
  },
  {
    id: "d4",
    name: "Dr. James Wilson",
    specialty: "pediatrics",
    hospital: "Children's Health Center",
    location: "Family Medical Complex",
    rating: 4.9,
    reviewCount: 203,
    experience: 15,
    fee: 60,
    currency: "USD",
    availableDays: ["Monday", "Tuesday", "Thursday", "Friday"],
    bio: "Dr. James Wilson is a compassionate pediatrician dedicated to providing comprehensive care for children from birth through adolescence.",
    image: "/images/doctor-4.jpg"
  },
  {
    id: "d5",
    name: "Dr. Lisa Park",
    specialty: "orthopedics",
    hospital: "Sports Medicine Center",
    location: "Athletic Medical Building",
    rating: 4.6,
    reviewCount: 78,
    experience: 10,
    fee: 100,
    currency: "USD",
    availableDays: ["Monday", "Wednesday", "Thursday"],
    bio: "Dr. Lisa Park specializes in sports medicine and orthopedic surgery. She works with athletes and active individuals to treat and prevent injuries.",
    image: "/images/doctor-5.jpg"
  },
  {
    id: "d6",
    name: "Dr. Robert Martinez",
    specialty: "general",
    hospital: "Community Health Clinic",
    location: "Eastside Medical Center",
    rating: 4.5,
    reviewCount: 167,
    experience: 20,
    fee: 45,
    currency: "USD",
    availableDays: ["Monday", "Tuesday", "Wednesday", "Friday"],
    bio: "Dr. Robert Martinez has been serving the community for over 20 years. He focuses on family medicine and preventive healthcare.",
    image: "/images/doctor-6.jpg"
  },
  {
    id: "d7",
    name: "Dr. Anna Kowalski",
    specialty: "cardiology",
    hospital: "Heart & Vascular Institute",
    location: "Medical District, Tower B",
    rating: 4.8,
    reviewCount: 92,
    experience: 14,
    fee: 110,
    currency: "USD",
    availableDays: ["Tuesday", "Thursday", "Friday"],
    bio: "Dr. Anna Kowalski specializes in preventive cardiology and cardiac imaging. She is passionate about heart disease prevention in women.",
    image: "/images/doctor-7.jpg"
  },
  {
    id: "d8",
    name: "Dr. David Thompson",
    specialty: "dermatology",
    hospital: "Advanced Dermatology Center",
    location: "Downtown Medical Tower",
    rating: 4.7,
    reviewCount: 134,
    experience: 11,
    fee: 90,
    currency: "USD",
    availableDays: ["Monday", "Wednesday", "Friday"],
    bio: "Dr. David Thompson is an expert in treating complex skin conditions and performing advanced cosmetic procedures.",
    image: "/images/doctor-8.jpg"
  },
  {
    id: "d9",
    name: "Dr. Maria Garcia",
    specialty: "pediatrics",
    hospital: "Children's Health Center",
    location: "Family Medical Complex",
    rating: 4.8,
    reviewCount: 178,
    experience: 9,
    fee: 55,
    currency: "USD",
    availableDays: ["Monday", "Tuesday", "Thursday", "Saturday"],
    bio: "Dr. Maria Garcia is a pediatrician with special interest in childhood development and behavioral health.",
    image: "/images/doctor-9.jpg"
  },
  {
    id: "d10",
    name: "Dr. John Miller",
    specialty: "orthopedics",
    hospital: "Joint & Spine Center",
    location: "Surgical Specialists Building",
    rating: 4.9,
    reviewCount: 145,
    experience: 22,
    fee: 130,
    currency: "USD",
    availableDays: ["Tuesday", "Wednesday", "Friday"],
    bio: "Dr. John Miller is a highly experienced orthopedic surgeon specializing in joint replacement and spine surgery.",
    image: "/images/doctor-10.jpg"
  }
];

export const appointments: Appointment[] = [
  {
    id: "a1",
    doctorId: "d1",
    doctorName: "Dr. Sarah Ahmed",
    patientName: "John Smith",
    patientEmail: "john.smith@email.com",
    patientPhone: "+1 555-0101",
    date: "2025-01-20",
    time: "09:00",
    reason: "Annual checkup and blood pressure monitoring",
    status: "pending",
    createdAt: "2025-01-10T10:30:00Z"
  },
  {
    id: "a2",
    doctorId: "d2",
    doctorName: "Dr. Michael Chen",
    patientName: "Emma Johnson",
    patientEmail: "emma.j@email.com",
    patientPhone: "+1 555-0102",
    date: "2025-01-22",
    time: "14:00",
    reason: "Follow-up after ECG results",
    status: "confirmed",
    createdAt: "2025-01-09T14:00:00Z"
  },
  {
    id: "a3",
    doctorId: "d1",
    doctorName: "Dr. Sarah Ahmed",
    patientName: "Michael Brown",
    patientEmail: "m.brown@email.com",
    patientPhone: "+1 555-0103",
    date: "2025-01-21",
    time: "11:00",
    reason: "Persistent cough for 2 weeks",
    status: "pending",
    createdAt: "2025-01-11T09:15:00Z"
  },
  {
    id: "a4",
    doctorId: "d4",
    doctorName: "Dr. James Wilson",
    patientName: "Sarah Davis",
    patientEmail: "sarah.d@email.com",
    patientPhone: "+1 555-0104",
    date: "2025-01-23",
    time: "10:00",
    reason: "Child vaccination appointment",
    status: "pending",
    createdAt: "2025-01-11T16:45:00Z"
  }
];

export const specialties: SpecialtyOption[] = [
  { id: "general", name: "General Practice" },
  { id: "cardiology", name: "Cardiology" },
  { id: "dermatology", name: "Dermatology" },
  { id: "pediatrics", name: "Pediatrics" },
  { id: "orthopedics", name: "Orthopedics" }
];
